// api/export/pdf/route.ts
// Generates a PDF receipt report for an org's receipts in a given month

import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase-server'
import { Receipt } from '@/types'
import { formatCurrency, formatDate } from '@/lib/utils'

export async function GET(req: NextRequest) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

    const { data: member } = await supabase
      .from('org_members')
      .select('org_id, organizations(name)')
      .eq('user_id', user.id)
      .single()

    if (!member) return NextResponse.json({ error: 'No org found' }, { status: 404 })

    const orgId = member.org_id
    const org = member.organizations as unknown as { name: string } | null
    const orgName = org?.name ?? 'Your Business'

    const month = req.nextUrl.searchParams.get('month') ?? new Date().toISOString().slice(0, 7)
    const [year, mo] = month.split('-').map(Number)

    const startDate = `${year}-${String(mo).padStart(2, '0')}-01`
    const endDate = new Date(year, mo, 0).toISOString().split('T')[0]

    const { data: receipts } = await supabase
      .from('receipts')
      .select('*')
      .eq('org_id', orgId)
      .gte('date', startDate)
      .lte('date', endDate)
      .order('date', { ascending: true })

    const rows = (receipts as Receipt[]) ?? []
    const total = rows.reduce((s, r) => s + Number(r.amount), 0)
    const taxTotal = rows.reduce((s, r) => s + Number(r.tax_amount ?? 0), 0)

    const monthLabel = new Date(year, mo - 1, 1).toLocaleString('default', { month: 'long', year: 'numeric' })

    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; color: #111; font-size: 13px; padding: 40px; }
  h1 { color: #059669; font-size: 22px; margin-bottom: 4px; }
  .sub { color: #6b7280; font-size: 12px; margin-bottom: 32px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
  th { background: #f9fafb; border-bottom: 2px solid #e5e7eb; text-align: left; padding: 8px 12px; font-size: 11px; text-transform: uppercase; color: #6b7280; }
  td { border-bottom: 1px solid #f3f4f6; padding: 8px 12px; }
  .total-row { font-weight: bold; font-size: 14px; }
  .footer { color: #9ca3af; font-size: 11px; margin-top: 40px; }
</style>
</head>
<body>
<h1>TrueFlio — ${orgName}</h1>
<p class="sub">Expense Report · ${monthLabel}</p>
<table>
<thead>
<tr><th>Date</th><th>Vendor</th><th>Category</th><th>Amount</th><th>Tax</th><th>Channel</th></tr>
</thead>
<tbody>
${rows.map(r => `<tr>
  <td>${formatDate(r.date)}</td>
  <td>${r.vendor_name ?? '—'}</td>
  <td>${r.category}</td>
  <td>${formatCurrency(r.amount, r.currency)}</td>
  <td>${r.tax_amount ? formatCurrency(r.tax_amount, r.currency) : '—'}</td>
  <td>${r.uploaded_via}</td>
</tr>`).join('')}
<tr class="total-row">
  <td colspan="3">TOTAL</td>
  <td>${formatCurrency(total)}</td>
  <td>${formatCurrency(taxTotal)}</td>
  <td></td>
</tr>
</tbody>
</table>
<p class="footer">Generated by TrueFlio · trueflio.com · ${new Date().toLocaleDateString()}</p>
</body>
</html>`

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="trueflio-report-${month}.html"`,
      },
    })
  } catch (err) {
    console.error('export/pdf route failed:', err)
    return NextResponse.json({ error: 'Export failed' }, { status: 500 })
  }
}
